### ISSUE TITLE
Update through composer for Kirby 3.6

### ISSUE THREAD

**Issue by janstieler** [OblikStudio/kirby-git#26]
Hi,
how can I update kirby-git with the composer for Kirby 3.6?
If I use version "oblik/kirby-git": "^dev-dev", I get error messages. 
What version number have I to use in the composer.json for updating?

Cheers

**Comment by hdodov** [comment]
What error messages do you get? 🤔

**Comment by janstieler** [comment]
Hi,
the error is:
> Could not parse version constraint ^dev-dev: Invalid version string "^dev-dev"

**Comment by hdodov** [comment]
This error means Composer doesn't understand the version you've specified. I think you can't use caret `^` together with `dev-dev`. You should simply try with `dev-dev`.

**Comment by hdodov** [comment]
I also just released version `1.3.0` with the Kirby 3.6 updates, so you should be able to use that as well.
