### ISSUE TITLE
Changes list broken in Kirby 3.7

### ISSUE THREAD

**Issue by IngoValente** [OblikStudio/kirby-git#29]
When updating to kirby 3.7, the changes list becomes invisible as soon as there are changes.
Not sure what happens here, and don't have any Kirby UI/Vue knowledge to understand what is going wrong.
It looks like its just a change in kirbys vue templating implementation. No errors in console, and the plugin works correctly apart from this visibility issue.

<img width="715" alt="Screenshot 2022-06-30 at 12 12 32" src="https://user-images.githubusercontent.com/4366126/176653594-4cade560-df7d-4166-b483-71adb891333a.png">

**Comment by hdodov** [comment]
Should be fixed now. Check [version 1.4.0](https://github.com/OblikStudio/kirby-git/releases/tag/1.4.0).

**Comment by IngoValente** [comment]
Perfect! Works like a charm now. Thanks hdodov!
