### ISSUE TITLE
autocommit changes?

### ISSUE THREAD

**Issue by rapsli** [OblikStudio/kirby-git#33]
is there a way to autocommit changes and push them. That would be a great and easy backkup.

**Comment by hdodov** [comment]
There is no built-in way, but as [mentioned in the docs](https://github.com/OblikStudio/kirby-git#api), you could use the [`Git` class](https://github.com/OblikStudio/kirby-git/blob/master/lib/Git.php) to do it yourself. I guess that something like this, using the [`page.update:after` hook](https://getkirby.com/docs/reference/plugins/hooks/page-update-after), would do the trick:

```php
use Oblik\KirbyGit\Git;

return [
	'hooks' => [
		'page.update:after' => function () {
			$git = new Git();
			$git->add();
			$git->commit('my message');
			$git->push();
		}
	]
];
```

**Comment by rapsli** [comment]
Great. That did the job!
