### ISSUE TITLE
.gitignore not being honoured

### ISSUE THREAD

**Issue by kevquirk** [OblikStudio/kirby-git#39]
Hi,

I'm running this plugin along with another plugin for tracking redirects and 404s. This other plugin uses an SQLite DB and I'm trying to add the DB to my `.gitignore` file on the repo, but kirby-git doesn't seem to be honouring it. The ignore works locally in VSCode, so I know it's not a problem with the file.

Any tips please?

**Comment by hdodov** [comment]
The plugin does not alter Git's functionality in any way. It just merely executes `git add`, `commit, `push`, and `pull`. Have you maybe forgot to upload the `.gitignore` file on your server?

**Comment by kevquirk** [comment]
No, it's definitely there. It may something on the server side, I'll keep digging. Thanks.

**Comment by kevquirk** [comment]
Doh! It was cached. Deleted the file from the cache and all is working now. Thanks again.
