### ISSUE TITLE
Unable to install with Kirby v4 via composer

### ISSUE THREAD

**Issue by srijan** [OblikStudio/kirby-git#41]
The <code>composer.json</code> in the current release requires <code>"getkirby/cms": "^3.7",</code>, which <code>^4.0.0</code> does not satisfy.

Full error:

    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - oblik/kirby-git[1.0.0, ..., 1.1.0] require getkirby/cms ^3.3 -&gt; found getkirby/cms[3.3.0, ..., 3.9.8] but it conflicts with your root composer.json require (^4.0.0).
        - oblik/kirby-git 1.2.0 requires getkirby/cms ^3.4 -&gt; found getkirby/cms[3.4.0, ..., 3.9.8] but it conflicts with your root composer.json require (^4.0.0).
        - oblik/kirby-git 1.3.0 requires getkirby/cms ^3.6 -&gt; found getkirby/cms[3.6.0, ..., 3.9.8] but it conflicts with your root composer.json require (^4.0.0).
        - oblik/kirby-git 1.4.0 requires getkirby/cms ^3.7 -&gt; found getkirby/cms[3.7.0, ..., 3.9.8] but it conflicts with your root composer.json require (^4.0.0).
        - Root composer.json requires oblik/kirby-git * -&gt; satisfiable by oblik/kirby-git[1.0.0, ..., 1.4.0].

(Originally published at: https://srijan.ch/notes/2023-11-28-001)

**Comment by hdodov** [comment]
Sorry, I've been busy lately. I'll try to make the plugin compatible with Kirby 4. In the meantime, PRs are welcome!

**Comment by coheredigital** [comment]
You can work around this by using an alias version in composer when installing Kirby 4.

`"getkirby/cms": "4.1.0 as 3.9.8"`

This of course means all your packages will now be checking their compatibility against version 3.9.8. Depending on the number of plugins your using this may not be worth the potential issues. Just wanted to share.

**Comment by hdodov** [comment]
I've published [version 2.0.0](https://packagist.org/packages/oblik/kirby-git#2.0.0) with support for Kirby 4. Could you try it out and let me know if it works?

**Comment by coheredigital** [comment]
Hey @hdodov, update looks to be working well for me. Thanks!
